# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{viddler}
  s.version = "0.3.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ilya Sabanin", 'Reenhanced LLC']
  s.date = %q{2010-08-14}
  s.description = %q{Ruby wrapper around Viddler.com[http://www.viddler.com] API.

== FEATURES:

Currently implemented API methods:

* viddler.videos.getRecordToken
* viddler.users.register
* viddler.users.auth
* viddler.users.getProfile
* viddler.users.setProfile
* viddler.users.setOptions
* viddler.videos.upload
* viddler.videos.getStatus
* viddler.videos.getDetails
* viddler.videos.getDetailsByUrl
* viddler.videos.setDetails
* viddler.videos.getByUser
* viddler.videos.getByTag
* viddler.videos.getFeatured
}
  s.email = %q{ilya.sabanin@gmail.com}
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    ".bundle/config",
     ".gitignore",
     ".rvmrc",
     "Gemfile",
     "Gemfile.lock",
     "History.txt",
     "License.txt",
     "README.txt",
     "Rakefile",
     "VERSION",
     "lib/ext/array.rb",
     "lib/ext/hash.rb",
     "lib/ext/open_struct.rb",
     "lib/viddler.rb",
     "lib/viddler/api_spec.rb",
     "lib/viddler/base.rb",
     "lib/viddler/comment.rb",
     "lib/viddler/multipart_params.rb",
     "lib/viddler/request.rb",
     "lib/viddler/user.rb",
     "lib/viddler/version.rb",
     "lib/viddler/video.rb",
     "test/fixtures/embed_code.txt",
     "test/test_helper.rb",
     "test/test_viddler.rb",
     "test/video.rb",
     "tmp/.gitignore",
     "viddler.gemspec"
  ]
  s.homepage = %q{http://viddler.rubyforge.org}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby wrapper around Viddler.com API.}
  s.test_files = [
    "test/test_helper.rb",
     "test/test_viddler.rb",
     "test/video.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.0.rc"])
      s.add_runtime_dependency(%q<rest-client>, [">= 0"])
      s.add_runtime_dependency(%q<mime-types>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 3.0.0.rc"])
      s.add_dependency(%q<rest-client>, [">= 0"])
      s.add_dependency(%q<mime-types>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 3.0.0.rc"])
    s.add_dependency(%q<rest-client>, [">= 0"])
    s.add_dependency(%q<mime-types>, [">= 0"])
  end
end

